import { Translations } from './types';

export const TEXTS: Record<string, Translations> = {
  'pt-BR': {
    title: 'NutriBusca AI',
    subtitle: 'Descubra as calorias e macronutrientes do seu alimento.',
    searchPlaceholder: 'Ex: Arroz com feijão, Coxinha, Abacate...',
    searchButton: 'Buscar informações nutricionais',
    loading: 'Analisando alimento...',
    errorGeneric: 'Ocorreu um erro ao buscar os dados. Tente novamente.',
    errorNotFound: 'Não conseguimos identificar esse alimento. Tente ser mais específico.',
    calories: 'Calorias',
    protein: 'Proteínas',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    fiber: 'Fibras',
    sugar: 'Açúcares',
    servingSize: 'Porção',
    nutritionalInfo: 'Informação Nutricional',
    macrosBreakdown: 'Distribuição de Macros',
  },
  'en-US': {
    title: 'NutriSearch AI',
    subtitle: 'Discover calories and macronutrients for your food.',
    searchPlaceholder: 'Ex: Rice and beans, Burger, Avocado...',
    searchButton: 'Search Nutrition Info',
    loading: 'Analyzing food...',
    errorGeneric: 'An error occurred while fetching data. Please try again.',
    errorNotFound: 'We could not identify this food. Please be more specific.',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fats',
    fiber: 'Fiber',
    sugar: 'Sugars',
    servingSize: 'Serving Size',
    nutritionalInfo: 'Nutritional Information',
    macrosBreakdown: 'Macro Distribution',
  },
};
